server:
  port: 8000

spring:
  application:
    name: cloud-order-server

eureka:
  client:
    register-with-eureka: true          #表示自己是否注册进入eureka注册中心，true表示要注册
    fetch-registry: true                #是否从eurekaServer抓取已有的注册信息，默认是true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka       #单机版
      defaultZone: http://eureka7001.com:7001/eureka       #单机版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka      #集群版

