server:
  port: 7001

#单机版如下
#eureka:
#  instance:
#    hostname: localhost #eureka服务端实例名称
#  client:
#    register-with-eureka: false    #表示不向注册中心注册自己
#    fetch-registry: false          #表示自己就是注册端，我的职责就是维护服务实例，并不需要去检索服务
#    service-url:
#      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#集群版：
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端实例名称
  client:
    register-with-eureka: false    #表示不向注册中心注册自己
    fetch-registry: false         #表示自己就是注册端，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka    #单机模式
#      defaultZone: http://eureka7002.com:7002      #集群： 7001与7002相互注册，注意修改了hosts文件
  server:
    enable-self-preservation: false           #禁用自我保护模式：只要服务不可用，立刻删除     自我保护模式：防止因网络卡顿问题而误杀服务
    eviction-interval-timer-in-ms: 2000       #发心跳的时间设置为2秒