server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment       #服务别名----注册zookeeper到注册中心名称
  cloud:
    zookeeper:
      connect-string: 192.168.74.1:2181

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: chenjinjie



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.abouerp.itlearn.entities

logging:
  level:
    org:
      jasig: trace

